### ISSUE TITLE
Post process automated tests

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#89] opened 2019-03-19 21:10 UTC
Step 1 (#84) creates the framework to create many scenarios of results. This step will create automatic and semi-automatic tests that we can run on the suite of results each time.

**Automatic tests**

These should be always TRUE or always FALSE rules we can automatically test and flag if they are not met. Ex:

- Every `reservoir.outflow` has data that is not `NaN` AND >= 0 acre-ft/month
- Powell operating tier slot has data for every year that is non `NaN`
- In January-March runs, MWD ICS creation/delivery should vary between traces. In April-December runs, MWD ICS creation/delivery should be the same for every trace.

**semi-automatic tests**

These will be diagnostic plots that the developer will need to inspect. We can automate the creation of the figures, but the inspection will be manual.  To start we can create:

- all `reservoir.outflow`, `reservoir.pool elevation`, `reservoir.inflow`

Please go ahead and list any others checks below.

**Comment by stighi** [comment] 2019-04-03 18:14
Test full extent of reservoir operating range for MTOM Development #84

**Comment by rabutler-usbr** [comment] 2019-04-03 18:44
Thanks @stighi for pointing out #84. I've closed #89 since it is the same as #84. I think this is part two that uses some automated tests (likely in R).

**Comment by cfelletter** [comment] 2019-04-05 18:24
Happy to help just want to do it in a way everyone is on board with. 

I've developed a generic check script to output when slots are <= 0 in my RW-RDF-Process-Plot and it could be incorporated into an automatic test. 

We could use output is rdf files to generate the plots. Currently RW-RDF-Process-Plot processes scenarios pretty inefficiently (one variable at a time) so we will want to create a custom script that processes and plots all the diagnostic plots.

**Comment by rabutler-usbr** [comment] 2019-04-08 22:17
Awesome, thanks @cfelletter. 

I have a few ideas I'd like to run by you, Sarah, and Jessie, but I've starting putting together a framework to help with this.

**Comment by cfelletter** [comment] 2020-01-24 21:07
@sbaker2423 and @stighi 
In light of the FG issue we found this month I propose we add a check  KNN_MTOM.FlamingGorgeDaily != NaN during any timestep of the run.  We can add a similiar check for KNN_MTOM.YampaDailyDeerlodgeDepleted, BlueMesaData.TargetDailyWhitewaterFlows, BlueMesaData.TargetDailyBlackCanyonFlows" & BlueMesaData.TargetDailyOutflowFromBlueMesa. These are important checks that the UB rules are working as intended.

**Comment by stighi** [comment] 2020-01-24 21:39
@cfelletter are you thinking that this would be a post processing check? Or would this be something we add to the ruleset (or initialization rule?) to insure the run will be able to complete correctly?

**Comment by cfelletter** [comment] 2020-01-27 15:39
@stighi its a post processing check since the run can solve without these slots it just can't solve correctly (e.g. Baseflow set the release when Spring flow failed to solve).

**Comment by cfelletter** [comment] 2021-05-25 18:46
@sbaker2423 can we close this?

**Comment by sbaker2423** [comment] 2021-05-25 21:46
Yeah - we can close this.

**Closed by sbaker2423** 2021-05-25 21:46 UTC
