### ISSUE TITLE
CAP EC/DCP ICS

### ISSUE THREAD

**Issue by apivarnik** [usbr/MTOM#119] opened 2020-04-23 16:26 UTC
Combine the EC/DCP ICS creation into a single slot. Have the model solve for the correct account

**Comment by stighi** [comment] 2020-04-23 16:31
This is currently implemented in the 24month study, and will be resolved during the model integration effort.  Do we think we need to do this separately in MTOM also for parallels runs during integration testing and verification?

**Comment by stighi** [comment] 2020-04-23 16:32
This is also a duplicate of issue # 115

**Closed** 2020-04-23 16:36 UTC
Labels: LC
