### ISSUE TITLE
Update with April official run info

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#10] opened 2018-04-19 00:12 UTC
@cfelletter It looks like @clhorner has committed all (most) of the April files to the dev branch. 

Will you work with her to issue a PR to move the dev into the master?

Then, maybe you and possibly @apivarnik can review prior to the merge. 

Thanks!

**Comment by clhorner** [comment] 2018-04-19 14:15
I don't want to merge the April files into the master quite yet. After committing the April files, we found a small hiccup in our MTOM run. It shouldn't affect much since its a small issue with one or two traces in 2023, but we're undecided at this point whether or not we want to rerun everything and update those files. 

I'll talk to Shana today and get a resolution on this.

**Comment by rabutler-usbr** [comment] 2018-04-19 14:59
👍 got it. Sorry for jumping the gun.

On Apr 19, 2018, at 8:15 AM, clhorner <notifications@github.com> wrote:

I don't want to merge the April files into the master quite yet. After
committing the April files, we found a small hiccup in our MTOM run. It
shouldn't affect much since its a small issue with one or two traces in
2023, but we're undecided at this point whether or not we want to rerun
everything and update those files.

I'll talk to Shana today and get a resolution on this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/usbr/MTOM/issues/10#issuecomment-382752838>, or mute
the thread

**Comment by cfelletter** [comment] 2018-04-20 17:43
Reposting here since I posted this comment on the closed merge request. 
@clhorner everything looks good and my run reproduced your results. When you make the final commit of adding the changing log be sure to use a tag like "closes #10" or similar and then this issue will be closed when we merge into the master. For more info on using keywords in commits:
https://help.github.com/articles/closing-issues-using-keywords/
Going forward we can keep issues open until merging them to the master and just use commit and keywords to close them. Be sure to use the keyword before the issue number , e.g. closes # and then it will track on Github

**Closed** 2018-04-25 01:08 UTC
